version: '3'
services:
  nginx:
    container_name: custom-nginx-v0.01
    image: ikasetebo/nginx-16.04:v0.01
    networks:
      - app_bridge
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx-conf/conf/conf.d/:/etc/nginx/conf.d/
      - ./nginx-conf/sites-available/default:/etc/nginx/sites-available/default
networks:
  app_bridge:
    driver: bridge



