version: '3'

services:
  app:
    container_name: laravel-v0.10
    image: ikasetebo/laravel:v0.08
    networks:
      - app_bridge
    pid: 'host'
    ports:
      - '8888:80'
  nginx:
    container_name: custom-proxy-v0.10
    image: ikasetebo/nginx-16.04:v10.00
    networks:
      - app_bridge
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./nginx-conf/conf/conf.d/:/etc/nginx/conf.d/
      - ./nginx-conf/sites-available/default:/etc/nginx/sites-enabled/default
networks:
  app_bridge:
    driver: bridge



